---
language: node_js
node_js:
    # we recommend testing addons with the same minimum supported node version as Ember CLI
    # so that your addon works for all apps
    - "10"

dist: trusty

addons:
    chrome: stable

cache:
    directories:
        - $HOME/.npm

env:
    global:
        # See https://git.io/vdao3 for details.
        - JOBS=1
        - CC_TEST_REPORTER_ID=3c17d30a957d0b5f06d932c3dd8ce9354df2b8d7769710d8827e6261445839d8

before_install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

branches:
    only:
        - master
        # npm version tags
        - /^v\d+\.\d+\.\d+/

jobs:
    fast_finish: true
    allow_failures:
        - env: EMBER_TRY_SCENARIO=ember-canary

    include:
        # runs linting and tests with current locked deps
        - stage: "Tests"
          name: "Tests"
          script:
              - npm run lint
              - npm run test:ember

        - stage: "Additional Tests"
          name: "Floating Dependencies"
          install:
              - npm install --no-package-lock
          script:
              - npm run test:ember

        # we recommend new addons test the current and previous LTS
        # as well as latest stable release (bonus points to beta/canary)
        - env: EMBER_TRY_SCENARIO=ember-lts-3.12
        - env: EMBER_TRY_SCENARIO=ember-lts-3.16
        - env: EMBER_TRY_SCENARIO=ember-release
        - env: EMBER_TRY_SCENARIO=ember-beta
        - env: EMBER_TRY_SCENARIO=ember-canary
        - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
        - env: EMBER_TRY_SCENARIO=ember-classic

script:
    - COVERAGE=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

after_script:
    - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
    - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
